###############################################################################
# AllStarLink 3 Packages
###############################################################################

asl3
asl3-asterisk
asl3-asterisk-config
asl3-asterisk-modules
asl3-menu
asl3-update-nodelist
asterisk-moh-opsound-gsm
dahdi-linux
