###############################################################################
# DVSwitch Core Packages
###############################################################################

dvswitch
dvswitch-base
dvswitch-server
analog-bridge
mmdvm-bridge
md380-emu
