###############################################################################
# P25 Connector Metadata
###############################################################################

CONNECTOR_NAME="P25"

CONNECTOR_VERSION="0.1.0-dev"

CONNECTOR_MODE="P25"

CONNECTOR_DESCRIPTION="P25 Connector"

CONNECTOR_AUTHOR="MW1COE"

CONNECTOR_SERVICES=""

CONNECTOR_STATUS="Placeholder"
