###############################################################################
# P25 Connector Metadata
###############################################################################

NAME="P25"

VERSION="0.1.0-dev"

MODE="P25"

DESCRIPTION="P25 Connector"

AUTHOR="MW1COE"

SERVICES=""

STATUS="Placeholder"
