###############################################################################
# M17 Connector Metadata
###############################################################################

CONNECTOR_NAME="M17"

CONNECTOR_VERSION="0.1.0-dev"

CONNECTOR_MODE="M17"

CONNECTOR_DESCRIPTION="Native M17 Connector"

CONNECTOR_AUTHOR="MW1COE"

CONNECTOR_SERVICES=""

CONNECTOR_STATUS="Placeholder"

CONNECTOR_REPO="https://github.com/nostar/MMDVM_CM.git"
CONNECTOR_BRANCH="master"
