###############################################################################
# M17 Connector Metadata
###############################################################################

NAME="M17"

VERSION="0.1.0-dev"

MODE="M17"

DESCRIPTION="Native M17 Connector"

AUTHOR="MW1COE"

SERVICES=""

STATUS="Placeholder"
