###############################################################################
# MMDVM Connector Metadata
###############################################################################

NAME="MMDVM"

VERSION="0.2.0-dev"

MODE="DMR"

DESCRIPTION="DVSwitch MMDVM Connector"

AUTHOR="MW1COE"

SERVICES="analog_bridge mmdvm_bridge md380-emu"

STATUS="Ready"
