###############################################################################
# MMDVM Connector Metadata
###############################################################################

CONNECTOR_NAME="MMDVM"
CONNECTOR_VERSION="0.2.0-dev"
CONNECTOR_MODE="DMR"
CONNECTOR_DESCRIPTION="DVSwitch MMDVM Connector"
CONNECTOR_AUTHOR="MW1COE"

CONNECTOR_SERVICES="analog_bridge mmdvm_bridge md380-emu"

NETWORK_SERVICES="md380-emu mmdvm_bridge analog_bridge"

RUNTIME_SERVICES="analog_bridge mmdvm_bridge"



CONNECTOR_STATUS="Ready"

NETWORK_SERVICES="md380-emu mmdvm_bridge analog_bridge"
RUNTIME_SERVICES="analog_bridge mmdvm_bridge"
