###############################################################################
# MMDVM Connector Metadata
###############################################################################

CONNECTOR_NAME="MMDVM"
CONNECTOR_VERSION="0.2.0-dev"
CONNECTOR_MODE="DMR"
CONNECTOR_DESCRIPTION="DVSwitch MMDVM Connector"
CONNECTOR_AUTHOR="MW1COE"

CONNECTOR_SERVICES="analog_bridge mmdvm_bridge md380-emu"

CONNECTOR_STATUS="Ready"
