NAME=Brandmeister
DESCRIPTION="Brandmeister DMR Network"

MODE=DMR
CONNECTOR=mmdvm

ADDRESS=3102.master.brandmeister.network
PORT=62031
PASSWORD=Wales4Ever

DEFAULT_TG=91
DEFAULT_SLOT=2

ANNOUNCE=custom/brandmeister-selected
