###############################################################################
# ASLDVSCTL Default Configuration
###############################################################################

# Station Information
CALLSIGN=
NODE=
DMR_ID=

# AllStarLink
ASL_PASSWORD=

# BrandMeister
BM_PASSWORD=

# TGIF
TGIF_PASSWORD=

# Defaults
DEFAULT_MODE=DMR
DEFAULT_TG=91
DEFAULT_SLOT=2

# USRP
USRP_HOST=127.0.0.1
USRP_PORT=32001
USRP_NODE=1999

# Logging
LOG_LEVEL=INFO
