###############################################################################
# Station Information
###############################################################################

CALLSIGN=KF0FYC
DMRID=3182057

NODE=450388

DESCRIPTION=Portable

LOCATION=Kansas

LATITUDE=
LONGITUDE=
