###############################################################################
# YSF Connector Metadata
###############################################################################

CONNECTOR_NAME="YSF"

CONNECTOR_VERSION="0.1.0-dev"

CONNECTOR_MODE="YSF"

CONNECTOR_DESCRIPTION="YSF Connector"

CONNECTOR_AUTHOR="MW1COE"

CONNECTOR_SERVICES=""

CONNECTOR_STATUS="Placeholder"
