###############################################################################
# YSF Connector Metadata
###############################################################################

NAME="YSF"

VERSION="0.1.0-dev"

MODE="YSF"

DESCRIPTION="YSF Connector"

AUTHOR="MW1COE"

SERVICES=""

STATUS="Placeholder"
