###############################################################################
# NXDN Connector Metadata
###############################################################################

NAME="NXDN"

VERSION="0.1.0-dev"

MODE="NXDN"

DESCRIPTION="NXDN Connector"

AUTHOR="MW1COE"

SERVICES=""

STATUS="Placeholder"
