###############################################################################
# NXDN Connector Metadata
###############################################################################

CONNECTOR_NAME="NXDN"

CONNECTOR_VERSION="0.1.0-dev"

CONNECTOR_MODE="NXDN"

CONNECTOR_DESCRIPTION="NXDN Connector"

CONNECTOR_AUTHOR="MW1COE"

CONNECTOR_SERVICES=""

CONNECTOR_STATUS="Placeholder"
